workflows:
  react_native_app:
    name: React Native CI/CD
    max_build_duration: 60
    instance_type: mac_mini_m1  # Peut être changé selon ton plan Codemagic
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - main
        - develop
    environment:
      vars:
        NODE_VERSION: 18
      flutter: stable
    scripts:
      - name: Installer les dépendances
        script: npm install
      - name: Linter et tests unitaires
        script: |
          npm run lint
          npm test
      - name: Générer le bundle JavaScript
        script: npm run build
    artifacts:
      - build/**/*
    publishing:
      email:
        recipients:
          - "ouagal.mahamat@yahoo.com"
