workflows:
  android_release:
    name: Build Android APK & AAB
    max_build_duration: 60
    instance_type: mac_mini_m1  

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main

    environment:
      vars:
        NODE_VERSION: 18
        JAVA_VERSION: 17
        GRADLEW_PATH: android/gradlew
      flutter: stable
    scripts:
      - name: Installer les dépendances
        script: npm install

      - name: Vérifier le code et exécuter les tests unitaires
        script: |
          npm run lint
          npm test

      - name: Build APK et AAB
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - "ouagal.mahamat@yahoo.com"
